
# ============================================================
#  Care Plus - Spring Boot Configuration
# ============================================================

spring.application.name=careplus-api
server.port=8080
cors.allowed-origins=*

# ---  Oracle DataSource  ------------------------------------
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521/orcl
spring.datasource.username=rm554019
spring.datasource.password=060304
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ---  JPA / Hibernate  --------------------------------------
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ---  JWT  --------------------------------------------------
# Troque por uma chave secreta forte em produ��o!
careplus.jwt.secret=cArePlusSecretKey2024!MudeMeEmProducao#XyZ
careplus.jwt.expiration-ms=86400000

# ---  Upload de arquivos  -----------------------------------
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# ---  Swagger UI  -------------------------------------------
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ---  CORS (ajustar para produ��o)  -------------------------
careplus.cors.allowed-origins=http://localhost:3000,http://localhost:19006

# ---  Logging  ----------------------------------------------
logging.level.br.com.careplus=DEBUG
logging.level.org.springframework.security=INFO


springdoc.data-rest.enabled=false
springdoc.hateoas.enabled=false
