INSERT INTO CP_LIGAS (NOME, PONTOS_MINIMO, PONTOS_MAXIMO, COR_HEX) VALUES ('Bronze', 0, 999, '#CD7F32');
INSERT INTO CP_LIGAS (NOME, PONTOS_MINIMO, PONTOS_MAXIMO, COR_HEX) VALUES ('Prata', 1000, 2999, '#C0C0C0');
INSERT INTO CP_LIGAS (NOME, PONTOS_MINIMO, PONTOS_MAXIMO, COR_HEX) VALUES ('Ouro', 3000, 5999, '#FBBF24');
INSERT INTO CP_LIGAS (NOME, PONTOS_MINIMO, PONTOS_MAXIMO, COR_HEX) VALUES ('Platina', 6000, 9999, '#E5E4E2');
INSERT INTO CP_LIGAS (NOME, PONTOS_MINIMO, PONTOS_MAXIMO, COR_HEX) VALUES ('Diamante', 10000, 19999, '#67E8F9');
INSERT INTO CP_LIGAS (NOME, PONTOS_MINIMO, PONTOS_MAXIMO, COR_HEX) VALUES ('Safira', 20000, 999999, '#0F52BA');

INSERT INTO CP_CATEGORIAS_DESAFIO (NOME, DESCRICAO) VALUES ('CORRIDA', 'Desafios de corrida');
INSERT INTO CP_CATEGORIAS_DESAFIO (NOME, DESCRICAO) VALUES ('HIDRATACAO', 'Desafios de hidratação');
INSERT INTO CP_CATEGORIAS_DESAFIO (NOME, DESCRICAO) VALUES ('MEDITACAO', 'Desafios de meditação');
INSERT INTO CP_CATEGORIAS_DESAFIO (NOME, DESCRICAO) VALUES ('NUTRICAO', 'Desafios de nutrição');
INSERT INTO CP_CATEGORIAS_DESAFIO (NOME, DESCRICAO) VALUES ('FORCA', 'Desafios de força');